blank_issues_enabled: false
contact_links:
  - name: 📚Documentation
    url: https://github.com/guzzle/guzzle/blob/7.11/docs/index.md
    about: Check the documentation before opening an issue.

  - name: ❓Support
    url: https://github.com/guzzle/.github/blob/master/.github/SUPPORT.md
    about: We use GitHub issues only to discuss bugs and new features.
